CREATE TABLE IF NOT EXISTS `rang` ( 
	`r_id` INT(11) NOT NULL AUTO_INCREMENT, 
	`r_type` INT(5) NOT NULL DEFAULT 0,
	PRIMARY KEY(`r_id`)
	) ENGINE=InnoDB CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `autorisations` ( 
`a_id` INT(11) NOT NULL AUTO_INCREMENT, 
`a_libelle` VARCHAR(10) NOT NULL DEFAULT "",
PRIMARY KEY(`a_id`)
) ENGINE=InnoDB CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `utilisateurs` ( 
	`u_id` INT(11) NOT NULL AUTO_INCREMENT, 
	`u_pseudo` VARCHAR(50) NOT NULL DEFAULT "",
    `u_mdp` VARCHAR(75) NOT NULL DEFAULT "",
	`u_rang_fk` INT(11) NOT NULL, CONSTRAINT `u_rang_fk_rang` FOREIGN KEY (`u_rang_fk`) REFERENCES `rang` (`r_id`) ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY(`u_id`)
	) ENGINE=InnoDB CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `rang_obtient` ( 
	`r_id_fk` INT(11) NOT NULL, CONSTRAINT `r_id_fk_auto` FOREIGN KEY (`r_id_fk`) REFERENCES `autorisations` (`a_id`) ON UPDATE CASCADE ON DELETE RESTRICT,
	`a_id_fk` INT(11) NOT NULL, CONSTRAINT `a_id_fk_rang` FOREIGN KEY (`a_id_fk`) REFERENCES `rang` (`r_id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB CHARSET=utf8mb4;